### ISSUE TITLE
Asset Link button on the map popups

### ISSUE THREAD

**Issue by wotnak** [symbioquine/farmOS_asset_link#28]
The Asset Link button is displayed on the map popups, but it appears behind the 'View assets in this location' button and when used it opens Asset Link only inside the small popup which is not really useful. Maybe it would be better to just don't display it on the map. Probably the best way to achieve it would be limiting button display only to the default asset display mode (on the map separate map_popup display mode is used).

![image](https://user-images.githubusercontent.com/52507690/221161388-7aa02ec5-b60d-44d3-8026-ca0c6fc0fb4b.png) ![image](https://user-images.githubusercontent.com/52507690/221161416-ed9d84c7-bc99-4ec7-a4da-da383c812d89.png)

**Comment by symbioquine** [comment]
Nice find @wotnak!

I'll have to see about the best strategy to fix this because I thought it was kind of nice that it does display on some of the pages related to the asset - e.g. `https://farmos.test/asset/1/logs` and `https://farmos.test/asset/1/assets` - but clearly this behaviour in the map popup isn't helpful.

**Comment by symbioquine** [comment]
Fixed by https://www.drupal.org/project/farmos_asset_link/releases/0.13.0
